### ISSUE TITLE
exhaustive ICNet code

### ISSUE THREAD

**Issue by NicholasBabaev** [fotisdr/ICNet#1]
Hello! Thank you for your paper and repo!
I am trying to translate ICNet in torch so your weights can be used, however, it seems not possible for me since the layers file does not describe(as I understood) all operations which are done inside ICNet model. Could you share all code for ICNet?

**Comment by fotisdr** [comment]
Hi, thanks for the interest in our work! 
It would be great to have a PyTorch version of our ICNet model as well, so I'd be more than willing to help with solving any uncertainties about the architecture of the model. Normally everything should be described in the paper into detail, but drop me an e-mail with anything that is not clear about the operations performed by ICNet model and I can help you construct the architecture in PyTorch (and load the provided weights). Hopefully we will be able to publish our Tensorflow code soon as well.
Fotis

**Comment by fotisdr** [comment]
Closed due to inactivity, but feel free to follow up via e-mail as mentioned.

**Comment by fotisdr** [comment]
Closed due to inactivity, but feel free to follow up via e-mail as mentioned.
